version: '3.8'

services:
  app_rizal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001-8003:8000"  # Mengunci pemetaan port fisik VM ke internal container
    volumes:
      - ./:/var/www
    depends_on:
      - db_rizal

  db_rizal:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password_lu
      MYSQL_DATABASE: parkir_rizal
    ports:
      - "3306:3306"
